services:
  - type: web
    name: petexpress-site-backend
    runtime: java
    rootDir: petexpress-site-backend/petexpress-site-backend
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/petexpress-site-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: APP_BASE_URL
        value: https://petexpress-site-backend.onrender.com
      - key: MERCADOPAGO_CHECKOUT_MODE
        value: production
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: petexpress-site
    runtime: static
    rootDir: .
    plan: free
    buildCommand: mkdir -p dist && cp -r *.html *.css *.js img dist/
    staticPublishPath: dist
